spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rag_workspace_db?currentSchema=rag
    username: postgres
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: rag
