spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 5003
